### PR TITLE
Update astropy-helpers to v1.3.1

### PR DESCRIPTION
**Pull request by bsipocz**
This is an automated update of the astropy-helpers submodule to v1.3.1. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed.

*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!*

### CODE REVIEW

**Comment by cdeil** [comment]
There's one fail in the docs build:
* https://travis-ci.org/astropy/regions/jobs/212825248#L737
* https://github.com/astropy/regions/blob/master/docs/plot_compound.py#L56

I don't see this locally, and it's not clear to me what the cause / fix is.
@bsipocz - How do you want to handle this? Split this out into a separate issue? Or do you have time to have a look / an idea what's going on?

**Comment by bsipocz** [comment]
@cdeil - I’m afraid this fail is already present on master (have just restarted the travis builds for the last merge commit) so is independent of the helpers. The runs are using different sphinx versions, but I doubt that being the problem (there are failures with 1.5.1 and 1.5.3 and previous passes with 1.5.1 and 1.5.2). 
Astropy is the other package that got changed since, previous passes were with 1.3 while the current failures are with 1.3.1. I don’t yet see how that could be related but haven’t had much time to investigate.

**Comment by larrybradley** [comment]
The failure occurs when trying to run `docs/plot_compound.py`. 

`python setup.py build_sphinx` gives no errors/warnings for me, but I can reproduce the error by manually running `docs/plot_compound.py`.  The error occurs on line 53 (https://github.com/astropy/regions/blob/master/docs/plot_compound.py#L53) when trying to plot using a `wcsaxes` transform.  The result is a unit conversion error where the input unit (in `SkyCoord`?) somehow is `None`:

```
    new_val = self.unit.to(unit, self.view(np.ndarray),
AttributeError: 'NoneType' object has no attribute 'to'
```

The bug occurs in `astropy 1.3.1` but not `1.3`, but I'm not sure it's a `wcsaxes` or `SkyCoord` bug.

cc: @astrofrog

**Comment by cdeil** [comment]
I had forgotten about this PR.

@bsipocz @larrybradley - What's the status / action item here? Is it possible to wrap this up or is this blocked somehow, waiting for a new Astropy bugfix release?

**Comment by larrybradley** [comment]
I restarted the failing test and it passed.  This is merged now.

**Comment by cdeil** [comment]
@larrybradley - dank je

**Pull request merged**
