### PR TITLE
Integration of HEALPix MOCs as a MOCSkyRegion class.

### PR DESCRIPTION
**Pull request by bmatthieu3**
Following the python HEALPix workshop at CDS (https://github.com/astropy/astropy-healpix/wiki/Python-HEALPix-workshop) we found great to integrate MOCs in astropy/regions (maybe in a MOCSkyRegion or something like that).

Since #62, [MOCPy](https://github.com/cds-astro/mocpy) is now BSD-3 licensed and uses astropy-healpix instead of healpy.
@cdeil and I have built a doc and added more unit tests (pytest [coverage](https://travis-ci.org/cds-astro/mocpy/jobs/402209014) at 90%, the plot function of a MOC is not tested).

I created a special branch on the MOCPy repo where I did a little cleanup for integrating it in ``regions`` : 

* Code : https://github.com/cds-astro/mocpy/tree/MOCSkyRegion
* Doc & API : https://mocpy.readthedocs.io/en/mocskyregion/

There are 2 files that are necessary for computing MOCs : ``interval_set.py`` and ``moc.py``. The first describes the internal data structure of a MOC and thus is only used in MOC.py. The second implements the API of MOCPy.

 It would be great if you guys could review the code, read the doc and tell me what you think, what changes need to be done, which methods to readjust...

This refers to the discussion started in #62 .

@tboch @cdeil

### CODE REVIEW

**Comment by keflavich** [comment]
I'm inclined to have it here.  Having `astropy.regions` exist while `astropy/regions` simultaneously exists will be confusing.

**Comment by bsipocz** [comment]
@cdeil @keflavich - Not that this is my business, but I'm also strongly favour of having this here first. We had plans to move regions to astropy.regions, and as far as I know there isn't many outstanding issues left, so it may happen relatively soon anyway (e.g 3.2? depending of course how much time you guys will have to make it happen, I foresee that I will be able to help after 3.1, but it will be limited to the technical side of the transition, but not any feature content prior).

**Comment by cdeil** [comment]
@astrofrog or @larrybradley as Astropy core devs - OK to put MOC here in astropy.regions?

If yes, I'd volunteer to do a first detailed review here (although of course anyone is welcome to review / comment any time).

**Comment by larrybradley** [comment]
I also prefer that it goes here (i.e. the `regions` package) first.  `regions` will eventually be entirely moved as a subpackage of `astropy` (`astropy.regions`).

**Comment by cdeil** [comment]
@bmatthieu3 - I only see one commit here (ba4f2c582e867438e3d1f847e645882c8c7653a5) with only a change to the README !? Can you please update the PR to put the right files, or close this and start a new PR?

**Comment by bmatthieu3** [comment]
@cdeil - Currently the code is in the branch MOCSkyRegion of the MOCPy repo : https://github.com/cds-astro/mocpy/tree/MOCSkyRegion and consists of two files each containing one class:
* The interval_set.IntervalSet class describing the internal struct of a MOC.
* The moc.MOC class describing the MOC object (API [here](https://mocpy.readthedocs.io/en/mocskyregion/api.html) involving differents methods : union, difference, intersection, contains). Of course I can put these two files here.

I have some questions regarding the implementation in the regions API : 

* As I can see I should create a new MOCSkyRegion and MOCPixelRegion classes inherited from SkyRegion (.resp PixelRegion). Do you know examples, e.g. PRs that could guide me for implementing a new region type ?

* Should I move the code inside the mocpy.MOC and interval_set.IntervalSet classes into those two classes or should we use MOCPy directly as a PIP dependency and define a mocpy.MOC object as an attribute of the future MOCSkyRegion class ? 
I was just thinking we will need to put astropy-healpix as a dependency of regions as MOCs are heavily using it.

* We do not plot MOCs using matplotlib patches but by sampling the sky and determine whether each of these samples lies into the HEALPix cells of the MOC.Then I use [pcolormesh](https://matplotlib.org/gallery/images_contours_and_fields/pcolormesh_levels.html) to color pixels lying into the MOC with one color, and those who do not with an other color. I have seen PixelRegion has a plot method using mpl patches that is why I say that.

**Comment by bmatthieu3** [comment]
@cdeil I uploaded the files defining MOC objects into a newly regions/shapes/moc directory and their corresponding test files into shapes/tests.

I made a rebase --interactive to squash two commits into one and push forced it and I think the problem is that when performing the rebase --interactive I just got tagged as editor of too much passed commits (git rebase --interactive HEAD~N gives the history of the last N commits and you can edit, drop, squash them as you wish, but I think even if you do not touch some of them, you will still be tagged as contributor of them). Normally the first commit of this PR branch should be e53194e.

I also added astropy-healpix as a dependency for all the CI-tools. CircleCI gives weird errors which could be related to numpy maybe. (When installing the astropy-healpix dependency there is an import error of numpy too).
The tests pass when running `python setup.py test` locally. Here is the header of the command showing the version of python and dependencies I'm using locally : 

```
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.5.2, pytest-3.4.2, py-1.5.3, pluggy-0.6.0

Running tests with regions version 0.3.dev679.
Running tests in regions docs.

Date: 2018-08-23T14:40:30

Platform: Linux-4.4.0-131-generic-x86_64-with-Ubuntu-16.04-xenial

Executable: /usr/bin/python3.5

Full Python Version: 
3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.14.2
Scipy: 1.0.1
Matplotlib: 2.2.2
Cython: 0.28.5
Astropy: 3.0.1
Astropy-healpix: 0.2
Using Astropy options: remote_data: none.

```
Hope it can help. Thank you.

**Comment by cdeil** [comment]
@bmatthieu3 - Just some quick comments, I don't have much time this week unfortunately.

The `regions/shapes/text.py` I see in the diff here is unrelated, no? Did the git cat drag that in? How about closing this PR, and making a clean new one from latest master, copying over the files edits you have here?

You could make a PR with the CI changes to add astropy-healpix first and separately; that could go in very quickly without much discussion. Then you have that in place for your big PR.

Since we aim to merge this package into Astropy core as astropy.regions, MOCPy shouldn't be a dependency. You should put everything needed for the core MOC functionality here in this package.

Hope that helps a bit ...

**Comment by cdeil** [comment]
> You could make a PR with the CI changes to add astropy-healpix first and separately

Since yesterday we have a Python 3.7 build here for regions on travis-ci.
I just noticed that the latest stable version of astropy-healpix doesn't support PYthon 3.7 yet:
https://github.com/astrofrog/reproject/issues/158#issuecomment-415672566

So @bmatthieu3 - Either you wait a bit for astropy-healpix to support Python 3.7 and make a new release, or in `.travis.yml` you pip-install the dev version for now, that should work fine.

**Comment by bmatthieu3** [comment]
@cdeil Ok thank you for the precision, I'll go for pip-installing the dev version.

**Comment by bmatthieu3** [comment]
#212

**Pull request closed without merging**
