### PR TITLE
MNT: Drop Python 3.6/3.7 support, update min dependencies, switch to GA for CI

### PR DESCRIPTION
**Pull request by larrybradley**
Python 3.6 is now at end of life and is no longer supported.

This PR also adds Python 3.10 to the CI test matrix.

### CODE REVIEW

**Review by keflavich — APPROVED** [review]
Approve, but next thing: can we move to gh-actions?

**Comment by larrybradley** [comment]
Yes, I can switch to Actions (next PR)!

**Comment by keflavich** [comment]
:+1: from me on the newer changes, but it might be a good idea to ask for trained eyes on this

**Comment by larrybradley** [comment]
I've updated this PR to require the following minimum dependencies

* Python 3.8+
* numpy 1.18+
* matplotlib 3.1+
* astropy 5.0+ (LTS)

These are identical to the latest astropy LTS release, which will be useful for merging regions into astropy core.

This PR also switches the CI from Azure to GitHub Actions.

**Comment by larrybradley** [comment]
It's almost identical to `photutils` so I know it works! :smile:

**Pull request merged**
