### PR TITLE
Enable doctests

### PR DESCRIPTION
**Pull request by bsipocz**
On current master there are 6 error and 17 failures when doctests are enabled. This PR fixes the errors, and I feel that we should merge in commits from here with the exception (in case there are still failures) of the first to the upcoming release.

### CODE REVIEW

**Comment by bsipocz** [comment]
Locally this passes.

**Comment by cdeil** [comment]
There's CI fails here: https://travis-ci.org/astropy/regions/jobs/542065875#L1458

And one fail here: https://ci.appveyor.com/project/Astropy/regions/builds/25078976/job/cmhckttgxl0t663y#L406

@bsipocz - Can you find a way to avoid those?

Is it possible to skip the doctests on those builds?
(I mean, spending time on repr differences across versions isn't fun - avoid it if you can)

**Comment by cdeil** [comment]
Alternatively, you could also turn doctest off again here and we merge all these edits / fixes immediately. The diff is large, this should go in quickly.

**Comment by bsipocz** [comment]
If we really want to test on  32bit, then the image needs to be updated. Currently I'm unable to install mpl on it as there are no wheel,  and I cannot yum install a recent enough freetype. Falling back on ancient mpl that still has the wheels.

**Comment by bsipocz** [comment]
(another alternative though to make mpl an optional dependency for the docs, too).

**Comment by bsipocz** [comment]
There are some issues with the appveyor 2.7 build when mpl is installed.  Rather than spending more time in the rabbit hole I removed that job given that we plan to remove  python2 support after this release. 

Note that everything was fine before this PR, so I'm confident things are not worse that they would have been without the doctests being run.

**Comment by bsipocz** [comment]
I've run out of ideas about the appveyor build. Everything looks the same as for photutils and yet it doesn't work. And in addition, it used to work before this PR.

**Comment by bsipocz** [comment]
All green but with the caveat that the appveyor jobs are allowed to fail. I suggest that while they are being allowed to fail is to have extra case and look at the log of the seemingly passing builds before merging feature PRs.

**Comment by bsipocz** [comment]
(out of band discussion with @cdeil, we agreed that I merge this asap I get a green status, so he can proceed with releasing 0.4)

**Pull request merged**
