### PR TITLE
Bug: Compound regions do not preserve location of originals

### PR DESCRIPTION
**Pull request by keflavich**
In the CompoundRegion creation, it looks like bottom/top are swapped!

### CODE REVIEW

**Comment by keflavich** [comment]
My mistake making the branch here instead of on my fork; not sure why the GH interface didn't offer me the option.

This looks like it's revealing a lot of incorrect tests

**Comment by astrofrog** [comment]
Happy to review this once the tests are fixed

**Comment by keflavich** [comment]
@astrofrog I think tests are passing now, except for some things that are unrelated, but I don't know how to debug that.  I'm still too unfamiliar with the build infrastructure to understand how to handle issues of this variety.

**Review by astrofrog — APPROVED** [review]
This looks good! Agree that the failure is unrelated, so will go ahead and merge this and will investigate the failure separately.

**Pull request merged**
