### PR TITLE
Radius to width conversion for ellipse for DS9 and CRTF reader

### PR DESCRIPTION
**Pull request by sushobhana**
tried to solve #143 .

### CODE REVIEW

**Comment by keflavich** [comment]
These changes look like they might be fine, but describe the logic in comments so we understand it.  The `var[-1] *= 2` is for the angle, right?  The rest are for converting full-width into half-width or vice-versa.

**Comment by sushobhana** [comment]
yes, I saw that in elliptical annulus angle is optional, so checking odd no. of elements in coord list for angle.
I will add them in comments. The logic seems fine right?

**Comment by keflavich** [comment]
I think so. This is a good one to try to test *every* corner case, though.

**Comment by migueldvb** [comment]
If the multiplication is only needed for the radius values why not specifying [2:4] ?

```                               
              self.coord[2:4] = [x * 2 for x in self.coord[2:4]] 
```

**Comment by sushobhana** [comment]
Because ellipse can also represent an elliptical annulus and the no. of radius pairs are unknown.

**Comment by migueldvb** [comment]
Ah OK. We could have a test for an ellipse annulus region in `test_shape_object.py`?

**Comment by sushobhana** [comment]
@keflavich  I think this is good to go for now.

**Pull request merged**
