### PR TITLE
Update helpers v3.2.1

### PR DESCRIPTION
**Pull request by bsipocz**
This is an exact copy of #287 that has been reset from master given that we need to keep python2 support just for a little longer.

### CODE REVIEW

**Comment by bsipocz** [comment]
This will obviously need the rebase before merging, e.g. the pytest5 issues has been addressed in #288

**Comment by cdeil** [comment]
@bsipocz - Please trigger a new CI build here.

**Comment by bsipocz** [comment]
@cdeil - shall I rebase, too?

**Comment by cdeil** [comment]
ok

**Comment by cdeil** [comment]
Ah, I see, this PR drops Python 2 support, that wasn't clear to me before.

**So this should not be merged for now.**

When to drop Python 2 support is being discussed in #241

**Comment by bsipocz** [comment]
Yes, thus is milestoned to 0.6, that is in my understanding the first version that will be python 3 only.

**Comment by keflavich** [comment]
I'm :+1: on merging this and ditching py2 support from 0.5 forward

**Comment by bsipocz** [comment]
push the button then ;)

**Pull request merged**
