### PR TITLE
Polygon pixel region area calculation

### PR DESCRIPTION
**Pull request by kiyami**
Hello,

I would like to offer a new method for area calculation of PolygonPixelRegion class.
I implemented the "area" method with some test cases as "test_area" method in "regions/shapes/tests/test_polygon.py" file.
It may not be well optimized for high performance, but can be upgraded if necessary.

Note: This is my first pull request, apologies for possible mistakes. Please guide me for the rest of the process.

Thank you,
M. K. Erdim

### CODE REVIEW

**Comment by keflavich** [comment]
Looks useful!  A few requests:
1. could you add some documentation describing the algorithm?  
2. minor - your `Returns` docstrings are formatted a little wrong; the thing returned should be below the `-----`'s

It would be nice if someone else could review this, but we're shortstaffed in this repo.  A description of the algorithm should help us understand what to look for, at least.  And if there's a reference (paper, other implementation), it would be helpful to note that.

**Comment by kiyami** [comment]
Thank you,

I will prepare your requests soon and contact again.


________________________________
Gönderen: Adam Ginsburg <notifications@github.com>
Gönderildi: 17 Kasım 2020 Salı 19:11
Kime: astropy/regions <regions@noreply.github.com>
Bilgi: Kiyami <kiyami_erdim@hotmail.com>; Author <author@noreply.github.com>
Konu: Re: [astropy/regions] Polygon pixel region area calculation (#328)


Looks useful! A few requests:

  1.  could you add some documentation describing the algorithm?
  2.  minor - your Returns docstrings are formatted a little wrong; the thing returned should be below the -----'s

It would be nice if someone else could review this, but we're shortstaffed in this repo. A description of the algorithm should help us understand what to look for, at least. And if there's a reference (paper, other implementation), it would be helpful to note that.

**Comment by kiyami** [comment]
[polygon_area_algorihtm.pdf](https://github.com/astropy/regions/files/5567332/polygon_area_algorihtm.pdf)

Hello,
I prepared a PDF that describes the algorithm. I hope it explains enough.

**Comment by larrybradley** [comment]
@kiyami Thanks for the PR.  The current method uses the well-known and widely-used Shoelace (or Gauss' area) algorithm to compute the polygon area (https://en.wikipedia.org/wiki/Shoelace_formula).  The Shoelace algorithm also handles self-overlapping polynomials, which appears to be a limitation of your proposed method.  Can you provide an example as to how your proposed area algorithm is an improvement over the current implementation?

**Pull request closed without merging**
