### PR TITLE
Add annulus region

### PR DESCRIPTION
**Pull request by joleroi**
Open questions
- Did you want to add an annulus as special region, or somehow as composite of 2 circles?
- What do we do with ds9 strings like `annulus(121.5,3745.5,20,40,60)`, i.e. 2 annuli? I could image returning two annulus regions

### CODE REVIEW

**Comment by keflavich** [comment]
Yes, we want annuli.  They can probably be treated as composites of the form `outer-inner`.

Annuli objects from ds9 should return lists of annulia of length (n_radii-1).  For round-trip IO purposes, though, we probably need to make a ConcentricAnnuli object that would contain that list.

**Comment by joleroi** [comment]
> They can probably be treated as composites of the form outer-inner.

So this PR should be closed/updated?

**Comment by keflavich** [comment]
updated; do we have a good implementation of a difference composite region yet?

**Comment by joleroi** [comment]
We have this: https://github.com/astropy/regions/blob/master/regions/core/compound.py#L30

**Comment by cdeil** [comment]
@joleroi - Could you please add one assert statement to your tests to re-trigger a travis-ci build?

@joleroi @keflavich What's the conclusion of your discussion on this annulus shape?
OK to add as-is?

I'm 👍  to add it, ... we can always remove it or change the implementation when more general shapes go in, but for now something is better than nothing, no?

**Comment by cdeil** [comment]
@joleroi Do you have time to finish up this PR in the next two days for the 0.1 release? Or should we punt this one to the 0.2 milestone?

**Comment by astrofrog** [comment]
While I think circular annulus makes sense, I think we want to avoid implementing annulus regions for all different shapes in future.

**Comment by keflavich** [comment]
You mean instead we should implement them as something composites along the line of (bigcircleregion - littlecircleregion) ?

**Comment by cdeil** [comment]
I'm moving this to the 0.2 milestone.

**Comment by astrofrog** [comment]
> You mean instead we should implement them as something composites along the line of (bigcircleregion - littlecircleregion) ?

Yes, probably would make sense

**Comment by joleroi** [comment]
I've done something horrible :scream_cat: I don't really know what but I'll close this an make a follow-up PR

**Comment by bsipocz** [comment]
Hmm, we could have sort this out, I think you simply merged upstream into here rather than doing a clean rebase. 
Anyway, basically any git messup can be cleaned up, and this is the time to learn the tricks...

**Pull request closed without merging**
