### PR TITLE
Switching to standalone six to avoid deprecation warnings

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by astrofrog** [comment]
Should ``six`` be added to ``install_requires``?

**Comment by bsipocz** [comment]
Of course it should. I'm sorry for the sloppy job, will amend the commit.

**Comment by cdeil** [comment]
@bsipocz - Thanks!

I would suggest to close this PR, and then to drop Python 2 support in the next days: #241

Alternatively, feel free to just merge this in now, if you don't want to wait for the Python 2 decision.

**Comment by bsipocz** [comment]
Given all the CASA complications I think I would rather prefer to get this merged now. (and then of course would prefer to get rid of python2 sooner rather than later, but that's another story).

**Comment by cdeil** [comment]
@bsipocz - go ahead and merge it in when ready.

**Pull request merged**
