### PR TITLE
Update read.py

### PR DESCRIPTION
**Pull request by nitish705702**

### CODE REVIEW

**Comment by cdeil** [comment]
@nitish705702 - Please put something in the "description" field above what this PR does.

@keflavich - Thoughts?

**Comment by cdeil** [comment]
@keflavich - Is this PR a duplicate of #237 ? Can you merge one in and close the other?

**Comment by nitish705702** [comment]
No Sir

**Comment by keflavich** [comment]
Yes, I believe this is superceded by #237.  I'll close one of them once I've had a chance to review more carefully.

**Pull request closed without merging**
