### PR TITLE
Document available shapes, add some repr and tests

### PR DESCRIPTION
**Pull request by cdeil**
This PR:
- [x] Adds a 'shapes' section to the docs with an example how to create each available shape
- [x] Implements `repr` for every shape in a consistent way
- [x] Adds a test file for every shape and checks object creation and repr at the very least
- [x] A few minor misc improvements in other places.

I'll merge if travis-ci passes, this should be uncontroversial.

If someone wants to do a quick review, it's welcome of course.

### CODE REVIEW

**Comment by bsipocz** [comment]
@mwcraig - Any idea why this cannot pick up wcsaxes from ``openastronomy``? https://travis-ci.org/astropy/regions/jobs/147281656#L522 
Previously there were no problems, and it got picked up from the ``astropy`` channel.

**Comment by mwcraig** [comment]
Yeah, that is what happens when the package is messed up on a conda channel. Give me a few minutes to cook up a script to nuke and recopy.

**Comment by mwcraig** [comment]
@bsipocz -- the channel *should* be working again...

**Comment by mwcraig** [comment]
Ha, ha, just kidding...I'm still getting failures with reproject.

**Comment by mwcraig** [comment]
A little more information...it is working for *some* packages, I was hitting a failure on reproject/numpy 1.9, but the original build on the astropy channel seems to be broken. 😕

**Comment by mwcraig** [comment]
Looks like wcsaxes is working now, so that is progress...

**Comment by cdeil** [comment]
@bsipocz @mwcraig - Thanks for fixing the conda install issues while I was sleeping. :-)

I restarted the build and everything worked now.

Merging.

**Pull request merged**
