### PR TITLE
Geometry functions require angle in radians

### PR DESCRIPTION
**Pull request by larrybradley**
This fixes a bug where the angle input to the geometry functions was in degrees when it should be in radians.

There isn't currently a good regression test I can add for this because the bounding boxes for rectangles and ellipse are always square.  I'm fixing that in other PRs.

### CODE REVIEW

**Comment by cdeil** [comment]
@larrybradley - Thanks!

Feel free to merge your own PRs any time, if you think it's straightforward and there's nothing to discuss or something you want reviewed.

**Comment by larrybradley** [comment]
Appveyor appears to be failing because `Cython` is not being installed.  @bsipocz?

**Comment by bsipocz** [comment]
@larrybradley - It seems to me that the problem is more like that shapely is not available. I should get to the bottom of https://github.com/astropy/ci-helpers/issues/87 asap, so we won't have misleading logs.

**Comment by bsipocz** [comment]
I've pushed a fix directly to this branch, hope it's OK with you.

**Comment by larrybradley** [comment]
Thanks, @bsipocz.

**Pull request merged**
