### PR TITLE
ds9 parser that appears to work

### PR DESCRIPTION
**Pull request by keflavich**
right now supports box, circle, polygon, point

### CODE REVIEW

**Comment by keflavich** [comment]
TODO (cc @joleroi):

 * [ ] Unit tests for individual functions
 * [ ] Benchmarks.  How much time per region?  How does it scale with n(regions)?
 * [ ] Correctness tests
 * [ ] Comparison to @sosey's branch (both for correctness & speed)
 * [ ] Implementation of all region types...

**Comment by cdeil** [comment]
Would it be possible to merge this today so that people (specifically me) can start playing with this?
Further work can always be done in future PRs, no?

**Comment by keflavich** [comment]
Yes, this will be merged today.  Except it won't be this PR, it will be https://github.com/astropy/regions/pull/7 most likely.

**Comment by bsipocz** [comment]
@keflavich - Since #7 is merged is this PR still relevant?

**Comment by keflavich** [comment]
No... I think this *is* merged... strange that git didn't recognize it.  Some of the files were renamed but this is definitely out of date.

**Pull request closed without merging**
