### PR TITLE
mapped_J2000

### PR DESCRIPTION
**Pull request by sushobhana**
ISSUE: #65

### CODE REVIEW

**Comment by sushobhana** [comment]
output:
screenshot from 2018-02-22 23-04-53

**Comment by keflavich** [comment]
@sushobhana Could you post text snippets instead of screenshots of text?

That said, this looks fine.  It would be helpful to add a regression test too.  Basically, add the example you screenshotted as a test

**Comment by sushobhana** [comment]
will add the test soon.

**Comment by sushobhana** [comment]
@keflavich is it ok to go?

**Comment by keflavich** [comment]
No, there are several test failures.  However, I don't think they're related to what you did, so I've restarted the tests.  Let's see if they pass now.  If not, we may need to ask someone else for help.

**Comment by sushobhana** [comment]
few blank spaces in the last line were causing the trouble..seems good now!

**Pull request merged**
