### PR TITLE
Add documentation of the `.visual` metadata

### PR DESCRIPTION
**Pull request by keflavich**
WIP: needs to be expanded.

Addresses issue #64.

@cdeil, @joleroi - as we expand and complete this, please commit directly to this branch

### CODE REVIEW

**Comment by cdeil** [comment]
@keflavich - Please rebase.

**Comment by cdeil** [comment]
@keflavich - This PR is from May. Do you plan to still work on this? (It says WIP at the top) Or would it be OK to merge this in now and then you or anyone else can continue with other PRs any time?

**Comment by keflavich** [comment]
best merge this & raise a new issue

**Comment by cdeil** [comment]
Merging now. Thanks!

**Pull request merged**
