### PR TITLE
Add region copy methods

### PR DESCRIPTION
**Pull request by cdeil**
As mentioned in #266 I'd like to add copy methods for regions.

I looked around a bit, e.g. [here](https://docs.python.org/3/library/copy.html) and [here](https://pymotw.com/3/copy/index.html), and there's `__copy__` and `__deepcopy__` that we could implement.

However, looking at `SkyCoord`, that doesn't seem to be implemented there. So I'd suggest to follow that class, and add a `copy` method for regions.

@astrofrog @keflavich @larrybradley  @sushobhana or anyone interested - could you please have a look at the one example method and test fr `CirclePixelRegion.copy` here? Is it OK, or would you suggest some different implementation or test pattern?

I'll wait a day here for suggestions before going ahead and adding `copy` methods for many region classes.

### CODE REVIEW

**Comment by larrybradley** [comment]
LGTM, carry on!

**Comment by cdeil** [comment]
@keflavich or @larrybradley - Could you please review this?

I've added copy for circle, ellipse, rectangle and polygon here.
And would prefer to continue with other shapes in future PRs.

**Comment by cdeil** [comment]
We could also implement `copy` in a generic way if we have a list of data fields for each class. And we could allow changes to be made on copy, which is very commonly what people want: make a copy, but change a few fields. I'm not sure if this generic `copy` written once in the base class would work for now, for the annuli classes (see #279).

See example implementing this proposal for one class: https://github.com/astropy/regions/commit/93c36566360b1b4e2c556c59ae5192b71d1213b9

This is similar to what [replace](https://github.com/python/cpython/blob/d561f848b235f2011a43b705d112055b92fa2366/Lib/dataclasses.py#L1205-L1253) does for [dataclasses](https://docs.python.org/3/library/dataclasses.html)

**Comment by cdeil** [comment]
I'll merge this in now, because I've gone ahead and started to implement `rotate` (see #265) which requires this copy functionality. I'll open a new PR for that shortly where I also change the implementation of `copy`. Comments still welcome any time!

**Pull request merged**
